[package]
name = "auth"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7.1"

base64 = "0.11.0"
bytes = "0.4.12"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.6.1"

futures = {version = "0.3.1", features =["compat"]}

tera = "1.0.0-beta"
actix = "0.8.3"
actix-web = "1.0.9"
actix-session = "0.2.0"
actix-web-httpauth = "0.3.2"

oxide-auth = { git = "https://github.com/HeroicKatora/oxide-auth/", branch = "next" }
oxide-auth-actix = { git = "https://github.com/HeroicKatora/oxide-auth/", branch = "next" }

azure_sdk_core = { git = "https://github.com/zpgaal/AzureSDKForRust.git", branch = "gzp" }
azure_sdk_storage_core = { git = "https://github.com/zpgaal/AzureSDKForRust.git", branch = "gzp" }
azure_sdk_storage_table = { git = "https://github.com/zpgaal/AzureSDKForRust.git", branch = "gzp" }
