[package]
name = "auth"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7.1"

futures = {version = "0.3", features =["compat"]}

base64 = "0.11"
bytes = "0.4"
uuid = { version = "0.8", features = ["v4"] }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.6"
config ="0.9"

tera = "1.0.0-beta"
actix-rt = "1.0.0"
actix-web = "2.0.0-alpha.5"
actix-session = "0.3.0-alpha.3"
mount = "0.4.0"
router = "0.6.0"

url = "1.7"
oxide-auth = { git = "https://github.com/gzp-crey/oxide-auth", branch = "ring_16_actix_2" }
oxide-auth-actix = { git = "https://github.com/gzp-crey/oxide-auth", branch = "ring_16_actix_2" }

azure_sdk_core = { git = "https://github.com/gzp-crey/AzureSDKForRust.git", branch = "bump_depenedency_versions" }
azure_sdk_storage_core = { git = "https://github.com/gzp-crey/AzureSDKForRust.git", branch = "bump_depenedency_versions" }
azure_sdk_storage_table = { git = "https://github.com/gzp-crey/AzureSDKForRust.git", branch = "bump_depenedency_versions" }
