[package]
name = "shine-game"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[features]
wasm = ["wasm_wgpu", "wasm-bindgen", "wasm-bindgen-futures", "shine-ecs/wasm"]
native = ["native_wgpu", "tokio", "shine-ecs/native"]


[dependencies]
log = "0.4"
#glsl-to-spirv = "0.1"

tokio = {version = "0.2", features = ["rt-core"], optional = true}
native_wgpu = {package = "wgpu", verion = "0.5", optional = true}

wasm_wgpu = {package = "wgpu", git = "https://github.com/grovesNL/wgpu-rs.git", branch = "wasm1", optional = true}
wasm-bindgen = {version = "0.2", optional = true}
wasm-bindgen-futures = {version = "0.4", optional = true}

shine-input = {path = "../input", version = "0.1.0"}
shine-ecs = {path = "../ecs", version = "0.1.0"}

[dev-dependencies]
rand = "0.7"
permutohedron = "0.2"
