[package]
name = "shine-game"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[features]
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "shine-ecs/wasm"]
native = ["tokio", "shine-ecs/native"]


[dependencies]
log = "0.4"
serde = {vesrion = "1.0", features = ["derive"] }
serde_derive = "1.0"
config ="0.10"

futures = "0.3"
url = "2.1"
tokio = {version = "0.2", features = ["rt-core"], optional = true}

wgpu = {package = "wgpu", git = "https://github.com/gfx-rs/wgpu-rs.git", branch = "master"}

wasm-bindgen = {version = "0.2", optional = true}
wasm-bindgen-futures = {version = "0.4", optional = true}

shine-input = {path = "../input", version = "0.1.0"}
shine-ecs = {path = "../ecs", version = "0.1.0"}

[dev-dependencies]
rand = "0.7"
permutohedron = "0.2"
