[package]
name = "shine-input"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[features]
native = []
wasm = ["wasm-timer"]

[dependencies]
log = "0.4"

wasm-timer = {version = "0.2", optional = true}
