[package]
name = "shine-native"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"

shine-input = {path = "../input", version = "0.1.0"}
shine-game = {path = "../game", version = "0.1.0", features = ["native"]}
