[package]
name = "shine-web"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
serde = "1.0"
tera = "1.1"
actix-rt = "1.0"
actix-web = "2.0"
actix-files = "0.2"

#shine-core = {path = "../core", version = "0.1.0"}
