[package]
name = "shine-ecs"
version = "0.1.0"
authors = ["gzp-crey <gzp@creygames.com>"]
edition = "2018"

[dependencies]
log = "0.4"
futures = "0.3"

downcast-rs = "1.1"
legion = "0.2"
fxhash = "0.2"

[dev-dependencies]
env_logger = "0.7"
permutohedron = "0.2"
rand = "0.7"
