name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Test ecs
      run: |
        cd game/ecs
        cargo clippy --features native
        cargo test --features native -- --test-threads=1 
        
    - name: Test game
      run: |
        cd game/game
        cargo clippy --features native
        cargo test --features native -- --test-threads=1 
        
    - name: Build cooker
      run: |
        cargo clippy -p shine-cooker
        cargo build -p shine-cooker
      
    - name: Build game (native)
      run: |
        cargo clippy -p shine-native
        cargo build -p shine-native
